ALTER TABLE usuario AUTO_INCREMENT = 2;
ALTER TABLE testdetalle AUTO_INCREMENT = 1;
ALTER TABLE test AUTO_INCREMENT = 1;
ALTER TABLE persona AUTO_INCREMENT = 1;
ALTER TABLE indicadorprocedimiento AUTO_INCREMENT = 1;
ALTER TABLE indicador AUTO_INCREMENT = 1;
ALTER TABLE examenesvarios AUTO_INCREMENT = 1;
ALTER TABLE examenheces AUTO_INCREMENT = 1;
ALTER TABLE examenhemograma AUTO_INCREMENT = 1;
ALTER TABLE examenorina AUTO_INCREMENT = 1;
ALTER TABLE examenquimica AUTO_INCREMENT = 1;
ALTER TABLE enfermeriaprocedimiento AUTO_INCREMENT = 1;
ALTER TABLE consulta AUTO_INCREMENT = 1;
ALTER TABLE consultaindicador AUTO_INCREMENT = 1;

